### ISSUE TITLE
模块

### ISSUE THREAD

**Issue by xwh8965** [HdShare/HdTool#2]
哥 能否帮忙定制个模块功能 可以给💰

**Comment by HdShare** [comment]
> 哥 能否帮忙定制个模块功能 可以给💰

大概需求？

**Comment by xwh8965** [comment]
QQ艾特全体功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月31日(周五) 凌晨0:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HdShare/HdTool] 模块 (Issue #2)




  
哥 能否帮忙定制个模块功能 可以给💰
  
大概需求？

**Comment by HdShare** [comment]
> QQ艾特全体功能

很好，我不会

**Comment by xwh8965** [comment]
好吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月31日(周五) 凌晨1:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HdShare/HdTool] 模块 (Issue #2)




  
QQ艾特全体功能
  
很好，我不会
